[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TNRKit = "7dfc3ef0-df9b-475f-b8e2-b91f34f5d84d"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
